// examples/rsbuild-vue/src/pages/index.vue
<template>
  <div>
    <p>index.vue</p>
    <router-link to="/blog">
      blog
    </router-link> |
    <router-link to="/about">
      about
    </router-link> |
    <router-link to="/components">
      components
    </router-link> |
    <router-link to="/xxx/xxx">
      not exists
    </router-link> |
  </div>
</template>

// examples/vite-react/src/pages/index.tsx
import type { FC } from 'react'
import { Link } from 'react-router'

const index: FC = () => {
  return (
    <div>
      <p>index.tsx</p>
      <Link to="/blog">
        blog
      </Link>
      {' '}
      |
      <Link to="/about">
        about
      </Link>
      {' '}
      |
      <Link to="/components">
        components
      </Link>
      {' '}
      |
      <Link to="/xxx">
        not exists
      </Link>
    </div>
  )
}

export default index
